### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by M4R3Kcracks**
:) :zap::zap:

### CODE REVIEW

**Comment by digmorepaka** [comment]
no emojis 😢

**Comment by samdenty99** [comment]
*Gitmoji gonnne*

image

**Comment by M4R3Kcracks** [comment]
thx lol

**Comment by samdenty99** [comment]
Live https://wi-pwn.samdd.me/czech/

**Comment by TomHorvath1607** [comment]
Thank you so much, for Czech translation ;)

**Pull request merged**
